### ISSUE TITLE
not ideal title, missing or non-best-practice flags

### ISSUE THREAD

**Issue by matu3ba** [jvoisin/compiler-flags-distro#1]
1. Explain what c/c++ compilers the flags are compatible with (clang and gcc most likely). The title reads like the flags are general, whereas in C/C++ land there is no such thing for compiler flags.
2. `-fsanitize=signed-integer-overflow -fsanitize-undefined-trap-on-error` creates better code due to using the compiler_rt builtins xor cpu intrinsics, see https://gist.github.com/jrelo/f5c976fdc602688a0fd40288fde6d886
3. Please link best practice checks for known CVEs (ie clang-tidy) and/or other tools without noise or configuration effort.

Personal opinion:
- `-Wstring-conversion` could be added, because implicit `std::sting -> bool &` conversions, especially during function calls, are outright evil and not covered by `-Wall, -Werror, -Wpedantic` etc

Nice link also covering msvc: https://airbus-seclab.github.io/c-compiler-security/

**Comment by matu3ba** [comment]
See also https://github.com/airbus-seclab/c-compiler-security.

**Comment by matu3ba** [comment]
I guess the intention is to document status quo, so closing.

**Comment by jvoisin** [comment]
Indeed: this repository isn't recommendations or anything like this; it's simply documenting the current situation.

The goal is to be able to go make it easier to convince linux distributions to enable some flags, "since other are already doing it for ages".
