### ISSUE TITLE
Ubuntu's GCC and dpkg

### ISSUE THREAD

**Issue by eslerm** [jvoisin/compiler-flags-distro#2]
In Debian, compiler flags are implemented to protect their archive though dpkg. They expressly avoid changing gcc defaults. References in this repo point to Debian's gcc configs, I'd check [dpkg-buildflags](https://manpages.debian.org/testing/dpkg-dev/dpkg-buildflags.1.en.html).

Ubuntu inherits these dpkg flags. Flags from gcc and dpkg and are used to build the Ubuntu Archive.

GCC flags are required to build artifacts, like software users compile or snaps, or anything not the Ubuntu Archive. What is listed on https://wiki.ubuntu.com/ToolChain/CompilerFlags applies to GCC.

So, in a way, all dpkg compiler flags in Debian apply to Ubuntu and Ubuntu is additionally setting GCC hardening flags* (there are probably exceptions to this). I'm not sure how you want to track this, but I wanted to let you know.

Also, the Debian and Ubuntu archive recently received -mbranch-protection https://bugs.launchpad.net/ubuntu/+source/gcc-13/+bug/2040321 through dpkg. And Debian *recently* received -fcf-protection (which Ubuntu GCC acquired in 19.10) https://git.dpkg.org/cgit/dpkg/dpkg.git/commit/?id=8f5aca71c1435c9913d5562b8cae68b751dff663

**Comment by jvoisin** [comment]
I think we're only interested in distributed packages, and not in flags enabled by default for people compiling their own stuff.

I updated Debian and Ubuntu wrt. `-mbranch-protection` and `-fcf-protection` :)
