### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by xdaro** [jvoisin/compiler-flags-distro#5]
### **Urgent Security Alert!**

**Attention!** There has been a recent attempt to change the password on your GitHub account. If you do not recognize this activity, your account may be at risk.

**Immediate Action Required:** If you did not attempt to change the password, **change your password NOW** to protect your account from potential unauthorized access.

[**Click here to change your password and secure your account!**](#) _phishing link removed_

**Do not delay!** Your access and security are at risk!

**Comment by eslerm** [comment]
User reported with reference to this issue.
