### ISSUE TITLE
State that these are package build flags

### ISSUE THREAD

**Issue by eslerm** [jvoisin/compiler-flags-distro#6]
It should be mentioned that this repo tracks flags used to build distro packages. It does not necessarily represent the default flags of the distros C compiler. (e.g., flags that are only used in Ubuntu's dpkg, but not in gcc.)

This is important to make users aware of. If you use CI, the build flags here will not necessarily be used unless manually added. In the context of downstreams writing binaries for routers or multiplayer video games, this has a major security consequence. Also, artifacts made by these distros may not use build flags beyond what is set in gcc.

This is mentioned on https://github.com/jvoisin/compiler-flags-distro/issues/2 and the impact is described in https://bugs.launchpad.net/ubuntu/+source/gcc-14/+bug/2040321

It would be great to track which distros use hardening in C compilers in addition to their packaging system, but mentioning this gap is enough to warn users.

**Comment by jvoisin** [comment]
Sure, feel free to send a pull-request <3
